// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHMI_YVdyoQ4zMdFDBL_xHQzBKLNsgyo',
    appId: '1:463232764698:web:4c4dd704103364e9fb7aa3',
    messagingSenderId: '463232764698',
    projectId: 'eltagweed-elmoyasar',
    authDomain: 'eltagweed-elmoyasar.firebaseapp.com',
    storageBucket: 'eltagweed-elmoyasar.appspot.com',
    measurementId: 'G-4GYMD550DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ93i6Dg5-Li-SRXLPu1hySAh_3-VWdYk',
    appId: '1:463232764698:android:4bf30c00b9f104c5fb7aa3',
    messagingSenderId: '463232764698',
    projectId: 'eltagweed-elmoyasar',
    storageBucket: 'eltagweed-elmoyasar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHLZ9tT7e_L-2wmvC6okWwcwmba5QCaQ',
    appId: '1:463232764698:ios:6e2884a0200ed600fb7aa3',
    messagingSenderId: '463232764698',
    projectId: 'eltagweed-elmoyasar',
    storageBucket: 'eltagweed-elmoyasar.appspot.com',
    iosBundleId: 'com.example.eltagweedElmoyasar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMHLZ9tT7e_L-2wmvC6okWwcwmba5QCaQ',
    appId: '1:463232764698:ios:6e2884a0200ed600fb7aa3',
    messagingSenderId: '463232764698',
    projectId: 'eltagweed-elmoyasar',
    storageBucket: 'eltagweed-elmoyasar.appspot.com',
    iosBundleId: 'com.example.eltagweedElmoyasar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgHMI_YVdyoQ4zMdFDBL_xHQzBKLNsgyo',
    appId: '1:463232764698:web:bd76ac5a4da61b23fb7aa3',
    messagingSenderId: '463232764698',
    projectId: 'eltagweed-elmoyasar',
    authDomain: 'eltagweed-elmoyasar.firebaseapp.com',
    storageBucket: 'eltagweed-elmoyasar.appspot.com',
    measurementId: 'G-E9BGVGCZJP',
  );
}
